### PR TITLE
2 tests done, 1 pass, 1 fail.

### PR DESCRIPTION
**Pull request by lindamaok899**
l have done 2 tests: test_nr_coeffs_linear passes & test_coeff_names_linear, all tests pass.

### CODE REVIEW

**Comment by janosg** [comment]
The problem is that `assert_array_almost_equal` (imported as `aaae`) does not work with string datatype. If you just write: `assert tf.coeff_names_linear(self.incl_fac, 'short', 'f1', 3) == expected` it should work. Please fix this without making a new pull request, i.e. just appending it to the current one. The tutorial I gave you should tell you how that works.

**Comment by lindamaok899** [comment]
But isn't self.incl_fac the nose framework?

**Comment by janosg** [comment]
Sorry, you are right.The important part is that you replace aaae by assert ... == ...

**Comment by lindamaok899** [comment]
okay now it passes! thanks.

**Pull request merged**
